# Generated by Django 3.1.4 on 2020-12-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTestItem',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_option', models.CharField(max_length=250)),
                ('second_option', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('IE', 'TypeIE'), ('SN', 'TypeSN'), ('FT', 'TypeFT'), ('JP', 'TypeJP')], max_length=2)),
                ('inversion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalQuestionContent',
            fields=[
                ('questionID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logins', models.IntegerField(default=1)),
                ('likes_sent', models.IntegerField(default=0)),
                ('likes_receive', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('personality', models.CharField(max_length=4, null=True)),
                ('description', models.CharField(default='No description', max_length=300, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/user_profile_pictures/')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9, null=True)),
                ('searching_for', models.CharField(max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalQuestionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pydate.personalquestioncontent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pydate.personalquestioncontent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(null=True)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pydate.personalitytestitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_questions_match', models.CharField(choices=[('00', 'Agree None'), ('01', 'Agree 1 To 2'), ('10', 'Agree 2 To 1'), ('11', 'Agree Both')], default='00', max_length=2)),
                ('chatting_match', models.CharField(choices=[('00', 'Agree None'), ('01', 'Agree 1 To 2'), ('10', 'Agree 2 To 1'), ('11', 'Agree Both')], default='00', max_length=2)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
